// <auto-generated />
using System;
using CRUD_Web_MES.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_Web_MES.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_Web_MES.Model.u10000", b =>
                {
                    b.Property<string>("u10001")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("u10002")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10003")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10004")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10005")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10006")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10007")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10008")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10009")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u10010")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("u10011")
                        .HasColumnType("int");

                    b.Property<int>("u10012")
                        .HasColumnType("int");

                    b.Property<int>("u10013")
                        .HasColumnType("int");

                    b.Property<int>("u10014")
                        .HasColumnType("int");

                    b.Property<int>("u10015")
                        .HasColumnType("int");

                    b.Property<double>("u10016")
                        .HasColumnType("float");

                    b.Property<double>("u10017")
                        .HasColumnType("float");

                    b.Property<double>("u10018")
                        .HasColumnType("float");

                    b.Property<double>("u10019")
                        .HasColumnType("float");

                    b.Property<double>("u10020")
                        .HasColumnType("float");

                    b.Property<bool>("u10021")
                        .HasColumnType("bit");

                    b.Property<bool>("u10022")
                        .HasColumnType("bit");

                    b.Property<bool>("u10023")
                        .HasColumnType("bit");

                    b.Property<bool>("u10024")
                        .HasColumnType("bit");

                    b.Property<bool>("u10025")
                        .HasColumnType("bit");

                    b.Property<DateTime>("u10026")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u10027")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u10028")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u10029")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u10030")
                        .HasColumnType("datetime2");

                    b.HasKey("u10001");

                    b.ToTable("u10000");
                });

            modelBuilder.Entity("CRUD_Web_MES.Model.u20000", b =>
                {
                    b.Property<string>("u20001")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("u20002")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20003")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20004")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20005")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20006")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20007")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20008")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20009")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u20010")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("u20011")
                        .HasColumnType("int");

                    b.Property<int>("u20012")
                        .HasColumnType("int");

                    b.Property<int>("u20013")
                        .HasColumnType("int");

                    b.Property<int>("u20014")
                        .HasColumnType("int");

                    b.Property<int>("u20015")
                        .HasColumnType("int");

                    b.Property<double>("u20016")
                        .HasColumnType("float");

                    b.Property<double>("u20017")
                        .HasColumnType("float");

                    b.Property<double>("u20018")
                        .HasColumnType("float");

                    b.Property<double>("u20019")
                        .HasColumnType("float");

                    b.Property<double>("u20020")
                        .HasColumnType("float");

                    b.Property<bool>("u20021")
                        .HasColumnType("bit");

                    b.Property<bool>("u20022")
                        .HasColumnType("bit");

                    b.Property<bool>("u20023")
                        .HasColumnType("bit");

                    b.Property<bool>("u20024")
                        .HasColumnType("bit");

                    b.Property<bool>("u20025")
                        .HasColumnType("bit");

                    b.Property<DateTime>("u20026")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u20027")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u20028")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u20029")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("u20030")
                        .HasColumnType("datetime2");

                    b.HasKey("u20001");

                    b.ToTable("u20000");
                });
#pragma warning restore 612, 618
        }
    }
}
