using System.ComponentModel.DataAnnotations;

namespace IFM_ManufacturingExecutionSystems.Models.Database
{
    public class n00
    {
        [Key]
        public string c01 { get; set; }
        public string c02 { get; set; }
        public string c03 { get; set; }
        public string c04 { get; set; }
        public string c05 { get; set; }
        public string c06 { get; set; }
        public string c07 { get; set; }
        public string c08 { get; set; }
        public string c09 { get; set; }
        public string c10 { get; set; }
        public string c11 { get; set; }
        public string c12 { get; set; }
        public string c13 { get; set; }
        public string c14 { get; set; }
        public string c15 { get; set; }
        public string c16 { get; set; }
        public string c17 { get; set; }
        public string c18 { get; set; }
        public string c19 { get; set; }
        public string c20 { get; set; }
        public string c21 { get; set; }
        public string c22 { get; set; }
        public string c23 { get; set; }
        public string c24 { get; set; }
        public string c25 { get; set; }
        public string c26 { get; set; }
        public string c27 { get; set; }
        public string c28 { get; set; }
        public string c29 { get; set; }
        public string c30 { get; set; }
        public string c31 { get; set; }
        public string c32 { get; set; }
        public string c33 { get; set; }
        public string c34 { get; set; }
        public string c35 { get; set; }
        public string c36 { get; set; }
        public string c37 { get; set; }
        public string c38 { get; set; }
        public string c39 { get; set; }
        public string c40 { get; set; }
        public string c41 { get; set; }
        public string c42 { get; set; }
        public string c43 { get; set; }
        public string c44 { get; set; }
        public string c45 { get; set; }
        public string c46 { get; set; }
        public string c47 { get; set; }
        public string c48 { get; set; }
        public string c49 { get; set; }
        public string c50 { get; set; }
        public string c51 { get; set; }
        public string c52 { get; set; }
        public string c53 { get; set; }
        public string c54 { get; set; }
        public string c55 { get; set; }
        public string c56 { get; set; }
        public string c57 { get; set; }
        public string c58 { get; set; }
        public string c59 { get; set; }
        public string c60 { get; set; }
        public string c61 { get; set; }
        public string c62 { get; set; }
        public string c63 { get; set; }
        public string c64 { get; set; }
        public string c65 { get; set; }
        public string c66 { get; set; }
        public string c67 { get; set; }
        public string c68 { get; set; }
        public string c69 { get; set; }
        public string c70 { get; set; }
        public string c71 { get; set; }
        public string c72 { get; set; }
        public string c73 { get; set; }
        public string c74 { get; set; }
        public string c75 { get; set; }
        public string c76 { get; set; }
        public string c77 { get; set; }
        public string c78 { get; set; }
        public string c79 { get; set; }
        public string c80 { get; set; }
        public string c81 { get; set; }
        public string c82 { get; set; }
        public string c83 { get; set; }
        public string c84 { get; set; }
        public string c85 { get; set; }
        public string c86 { get; set; }
        public string c87 { get; set; }
        public string c88 { get; set; }
        public string c89 { get; set; }
        public string c90 { get; set; }
        public string c91 { get; set; }
        public string c92 { get; set; }
        public string c93 { get; set; }
        public string c94 { get; set; }
        public string c95 { get; set; }
        public string c96 { get; set; }
        public string c97 { get; set; }
        public string c98 { get; set; }
        public string c99 { get; set; }
    }
}
